# Generated by Django 3.0.7 on 2020-11-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interface',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_name', models.CharField(max_length=15)),
                ('i_url', models.CharField(max_length=500)),
                ('i_createtime', models.CharField(max_length=110)),
                ('i_updatetime', models.CharField(max_length=110)),
                ('i_exists', models.CharField(max_length=11)),
            ],
        ),
    ]
