# Generated by Django 3.0.7 on 2020-11-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_m_name', models.CharField(max_length=15)),
                ('c_name', models.CharField(max_length=20)),
                ('c_url', models.CharField(max_length=100)),
                ('c_method', models.CharField(max_length=10)),
                ('c_header', models.CharField(max_length=500)),
                ('c_param', models.CharField(max_length=500)),
                ('c_checktype', models.CharField(max_length=20)),
                ('c_checkvalue', models.CharField(max_length=20)),
                ('c_expectresult', models.CharField(max_length=20)),
                ('c_actualresult', models.CharField(max_length=20)),
                ('c_describe', models.CharField(max_length=110)),
                ('c_creator', models.CharField(max_length=11)),
                ('c_status', models.CharField(max_length=11)),
                ('c_createtime', models.CharField(max_length=110)),
                ('c_updatetime', models.CharField(max_length=110)),
                ('c_exists', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_p_name', models.CharField(max_length=15)),
                ('m_name', models.CharField(max_length=20)),
                ('m_tester', models.CharField(max_length=11)),
                ('m_describe', models.CharField(max_length=110)),
                ('m_status', models.CharField(max_length=11)),
                ('m_createtime', models.CharField(max_length=110)),
                ('m_updatetime', models.CharField(max_length=110)),
                ('m_exists', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('p_describe', models.CharField(max_length=110)),
                ('p_status', models.CharField(max_length=11)),
                ('p_createtime', models.CharField(max_length=110)),
                ('p_updatetime', models.CharField(max_length=110)),
                ('p_exists', models.BooleanField(default=True)),
            ],
        ),
    ]
